# Judge0 Configuration
# Set these passwords to match docker-compose.yml
REDIS_PASSWORD=YourJudge0RedisPassword
POSTGRES_USER=judge0
POSTGRES_PASSWORD=YourJudge0PostgresPassword
POSTGRES_DB=judge0

# Runtime configuration
MAX_QUEUE_SIZE=500
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true
ENABLE_COMMAND_LINE_ARGUMENTS=true
MAX_SUBMISSION_CPU_TIME_LIMIT=15.0
MAX_SUBMISSION_MEMORY_LIMIT=512000
